name: send android apk on release
on:
  release:
    types: [created]


jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Tests
        run: |
          npm run test
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: temurin
          java-version: 17
      
      - name: 'Create env file'
        run: |
          touch .env
          echo API_URL=${{ vars.API_URL }} >> .env
          cat .env
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

  send-apk-on-release:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send APK via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'New APK Build'
          body: "${process.env.GITHUB_EVENT.release.name} \n ${process.env.GITHUB_EVENT.release.tag_name} \n   ${process.env.GITHUB_EVENT.release.body} \n https://github.com/omar0404/ninjaz/actions/runs/8316294144/artifacts/1333122442"
          to: 'karim@ninjaz.ae'
          from: 'omar97.hassan97@gmail.com'

